---
title: "Untitled"
output: html_document
---

#############################################################################################################
#############             Secuencias Fq a fasta, gmsa, árbol, función de integración            #############
#############################################################################################################

  library("ShortRead")
  setwd ("C:/Users/crism/Documents/proyecto final robert/prueba/R2")
  
  # Cargar fastq
  fq1 <- readFastq("V350134218_L04_93_1.fq.gz")
  fq2 <- readFastq("V350134218_L04_93_2.fq.gz")
  
  # Extraer secuencias
  seqs1 <- sread(fq1)
  seqs2 <- sread(fq2)
  
  # Guardar como fasta (solo un ejemplo)
  writeXStringSet(seqs1, "secuencias_1.fasta")
  writeXStringSet(seqs2, "secuencias_2.fasta")
  
  library(msa)
  
  mis_secuencias <- readDNAStringSet("secuencias_2.fasta")
  alineamiento <- msa(mis_secuencias, method="Muscle")
  alineamiento
  
  library(ape)
  
  alineamiento_ape <- msaConvert(alineamiento, type="ape::DNAbin")
  
  distancias <- dist.dna(alineamiento_ape, model="raw")
  arbol <- nj(distancias)   # Neighbor Joining
  plot(arbol, cex=0.7)
  
  # FUNCIÓN GENERAL: analiza_sec_y_actualiza_arbol()
  library(Biostrings)
  

